builds:
- env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  main: ./cmd
  # dir: ./cmd
  # binary: buct_net_login
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  - arm
  - arm64
  - mipsle
  - mips64le
  goarm:
  - 5
  - 6
  - 7
  ignore:
    - goos: darwin
      goarch: arm
    - goos: darwin
      goarch: mipsle
    - goos: darwin
      goarch: mips64le
    - goos: windows
      goarch: mipsle
    - goos: windows
      goarch: mips64le
  flags:
  - -trimpath
  ldflags:
  - -s -w

archives:
  - format_overrides:
      - goos: windows
        format: zip
    replacements:
      darwin: macOS

checksum:
  algorithm: sha512